version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - apt-get update -y
      - apt-get install -y unzip
      - curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip -d /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - cd infra
      - terraform init -input=false

  build:
    commands:
      - terraform apply -input=false -auto-approve

artifacts:
  files:
    - '**/*'
